---
- name: Deploy NGINX (unprivileged) with X replicas and validate deployment on OpenShift
  hosts: localhost
  gather_facts: false

  vars:
    ocp_username: "{{ ansible_user }}"
    ocp_password: "{{ ansible_password }}"
    ocp_api: "{{ ocp_api_host | default('localhost') }}"
    ocp_namespace: "nginx-demo"
    num_replica: 3

  tasks:
    - name: Authenticate to OCP and generate token
      redhat.openshift.openshift_auth:
        username: "{{ ocp_username }}"
        password: "{{ ocp_password }}"
        host: "{{ ocp_api }}"
        validate_certs: no
      register: openshift_auth_results

    - name: Create project/namespace if it does not exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ ocp_namespace }}"
        state: present
        host: "{{ ocp_api }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"

    - name: Deploy NGINX (unprivileged) with X replicas
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: "{{ ocp_namespace }}"
          spec:
            replicas: "{{ num_replica }}"
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: "nginxinc/nginx-unprivileged:stable"
                    ports:
                      - containerPort: 8080 # the image listens on 8080
        host: "{{ ocp_api }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"

    - name: Expose NGINX deployment as a ClusterIP service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: "{{ ocp_namespace }}"
          spec:
            selector:
              app: nginx
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8080
            type: ClusterIP
        host: "{{ ocp_api }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"

    - name: Bounce NGINX deployment (scale 0 → num_replica)
      kubernetes.core.k8s_scale:
        api_version: apps/v1
        kind: Deployment
        name: nginx-deployment
        namespace: "{{ ocp_namespace }}"
        replicas: "{{ item }}"
        wait: true
        wait_timeout: 300
        host: "{{ ocp_api }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      loop:
        - 0
        - "{{ num_replica }}"

    - name: Get pods in nginx-demo namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ ocp_namespace }}"
        host: "{{ ocp_api }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      register: nginx_pods

    - name: Display pod status
      ansible.builtin.debug:
        msg: |
          Pods in namespace '{{ ocp_namespace }}':
          {% for pod in nginx_pods.resources %}
            - Name: {{ pod.metadata.name }}, Phase: {{ pod.status.phase }}
          {% endfor %}
